### ISSUE TITLE
Replace static example with our yawik search

### ISSUE THREAD

**Issue by cbleek** [yawik/yavue-nuxt#1]
@kilip I've created default nuxt app and copy&paste the example "paginated and sorted from backend" into a new [page](https://github.com/yawik/yavue-nuxt/blob/master/pages/jobs/search.vue)

The original Example:
https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side

Can you try to replace the example with our Yawik search, we're using in:

https://github.com/yawik/yavue/blob/master/src/components/Yavue.vue#L86

**Comment by kilip** [comment]
Yes, I can working on this search page.

**Comment by cbleek** [comment]
Great!
